kftpay:
  connectionTimeoutSeconds: 60
  responseTimeoutSeconds: 600
  httpDomain: 'test-merchant.kftpay.com.cn'
  merchant:
    notifyUrl: '"www.baidu.com"'
    tempZipFilePath: 'c:/zip'
    keyStorePath: 'e:/keystore/pfx.pfx'
    keyStorePassword: '123456'
    keyPassword: '123456'
    merchantId: '2024031400105169'
    ip: '127.0.0.1'
    wechat:
      appid: ''
    alipay:
      appid: ''
    sftp:
      domain: 'test-sftp.kftpay.com.cn'
      password: '105169'
