kftpay:
  connectionTimeoutSeconds: 60
  responseTimeoutSeconds: 600
  httpDomain: 'test-merchant.kftpay.com.cn'
  merchant:
    notifyUrl: 'www.baidu.com'
    tempZipFilePath: '/www/wwwroot/spring-boot-runwupay/target/temp/test.zip'
    keyStorePath: '/www/wwwroot/spring-boot-runwupay/target/temp/pfx.pfx'
    keyStorePassword: '123456'
    keyPassword: '123456'
    merchantId: '2024031400105169'
    ip: '127.0.0.1'
    wechat:
      appid: ''
    alipay:
      appid: ''
    sftp:
      domain: '183.56.161.108'
      password: '105169'
  test:
    tempZipFileName: 'test.zip'
    tempZipFilePath: '/www/wwwroot/spring-boot-runwupay/target/temp/test.zip'
    keyStorePath: '/www/wwwroot/spring-boot-runwupay/target/temp/pfx.pfx'
    keyStorePassword: '123456'
    keyPassword: '123456'
    merchantId: '2024031400105169'
    sftp:
      domain: 'test-sftp.kftpay.com.cn'
      password: '105169'
