kftpay:
  connectionTimeoutSeconds: 60
  responseTimeoutSeconds: 600
  httpDomain: '183.56.161.108'
  merchant:
    tempZipFilePath: 'c:/zip'
    keyStorePath: 'e:/keystore/pfx.pfx'
    keyStorePassword: ''
    keyPassword: ''
    merchantId: '2024031400105169'
    ip: '127.0.0.1'
    wechat:
      appid: ''
    alipay:
      appid: ''
    sftp:
      domain: 'test-sftp.kftpay.com.cn'
      account: '2024031400105169'
      password: ''


